### ISSUE TITLE
Doesn't work in Vue.js 2.0

### ISSUE THREAD

**Issue by bobbygerez** [greyby/vue-spinner#14]
Please add this to your documentation. I thought there was a problem in implementing but after I read the issues and found out that  it doesn't really work in Vue.js 2.0. Nice project  anyway and I hope you will support Vue.js 2.0. TY

**Comment by Matoo125** [comment]
Thanks for note. I just also tried to use with 2.0, so you saved my time looking for a problem.

**Comment by greyby** [comment]
Thank you for the feedback. I had added notes to README.

**Comment by justinledford** [comment]
This worked fine for me in Vue 2

**Comment by amoshydra** [comment]
Can confirm. This is working for me on Vue 2.3.4

```vue
<template>
  <div>
    <vue-spinner :loading="isLoading" color="#102938" size="20px"></vue-spinner>
  </div>
</template>

<script>
import SyncLoader from 'vue-spinner/src/SyncLoader';
export default {
  components: {
    'vue-spinner': SyncLoader,
  },
  data() {
    return {
      isLoading: false,
    };
  },
}
</script>
```

**Comment by arifhussain353** [comment]
@amoshydra  yes working with `"vue": "^2.3.4"`

**Comment by shtse8** [comment]
Yes, it is working with vue 2
