### ISSUE TITLE
ParseError: Unexpected token when trying to import

### ISSUE THREAD

**Issue by nivv** [greyby/vue-spinner#2]
I'm getting the below error when trying to import any of the loaders. I've tried to create my own components with the same contents and that works fine. 

```javascript
import PulseLoader from 'vue-spinner/src/PulseLoader.vue'
```

```bash
[12:38:54] gulp-notify: [Laravel Elixir] Browserify Failed!: Unexpected token

/Users/user/projects/vue-project/node_modules/vue-spinner/src/PulseLoader.vue:1
<template>
^
ParseError: Unexpected token
```

**Comment by greyby** [comment]
Can you provide the code?

**Comment by nivv** [comment]
Main.js (using browserify/vueify)

```javascript
var Vue = require('vue');
Vue.use(require('vue-resource'));

import PulseLoader from 'vue-spinner/src/PulseLoader.vue';


new Vue({
    el: '#app',

    components: {
        PulseLoader
    }
});
```

If I copy the contents from PulseLoader.vue to my own component dir it loads fine. I'm guessing there's some problem with my build tool chain.

**Comment by greyby** [comment]
Please turn on vue debugging mode to see the error log. `Vue.config.debug = true`

**Comment by cyberdummy** [comment]
Its because browserify will not pass included files from the node_modules folder to its transformers (vueify).

```js
import { PulseLoader } from 'vue-spinner/dist/vue-spinner.min';
```

As an import line should work.

**Comment by greyby** [comment]
Thank you @cyberdummy . I had update the README.

**Comment by Alan0625** [comment]
dfsafasfasfasfasfas
